### ISSUE TITLE
S3DIS preprocess

### ISSUE THREAD

**Issue by EricLina** [Gofinge/PointTransformerV2#25]
When preprocess Stanford3dDataset_v1.2_Aligned_Version using preprocess_s3dis.py, an error occured
> multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "Env/miniconda3/envs/pcr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "Env/miniconda3/envs/pcr/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "PointTransformerV2-main/pcr/datasets/preprocessing/s3dis/preprocess_s3dis.py", line 39, in parse_room
    obj = np.loadtxt(object_path)
  File "Env/miniconda3/envs/pcr/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1338, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "Env/miniconda3/envs/pcr/lib/python3.8/site-packages/numpy/lib/npyio.py", line 999, in _read
    arr = _load_from_filelike(
ValueError: the number of columns changed from 6 to 5 at row 180389; use `usecols` to select a subset and avoid this error
"""

>The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "PointTransformerV2-main/pcr/datasets/preprocessing/s3dis/preprocess_s3dis.py", line 114, in <module>
    main_process()
  File "PointTransformerV2-main/pcr/datasets/preprocessing/s3dis/preprocess_s3dis.py", line 107, in main_process
    pool.starmap(parse_room, [(room, opt.source_root, opt.save_root, opt.parse_normals)
  File "Env/miniconda3/envs/pcr/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "Env/miniconda3/envs/pcr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
ValueError: the number of columns changed from 6 to 5 at row 180389; use `usecols` to select a subset and avoid this error

**Comment by EricLina** [comment]
![image](https://user-images.githubusercontent.com/60723818/222134339-a40074ed-aa48-4ffe-a029-8387be01c791.png)
Stanford3dDataset_v1.2_Aligned_Version/Area_5/hallway_6/Annotations/ceiling_1.txt, delete line 180389.

**Comment by Gofinge** [comment]
Hi, as mentioned in the readme and issue #8, a bug exists in the raw S3DIS dataset aligned version. The preprocessing script will be more robust in the next version of our codebase, which will be released recently.

**Comment by EricLina** [comment]
> 

Thanks for your reply. I will close this issue.
