### ISSUE TITLE
The original S3DIS data contains some bugs data need manually fix it. xxx^@xxx

### ISSUE THREAD

**Issue by Satyapalsinh10** [Gofinge/PointTransformerV2#37]
Hi I wanted to clarify the below comment in your repo.
The original S3DIS data contains some bugs data need manually fix it. xxx^@xxx

when i try to run the ython pcr/datasets/preprocessing/s3dis/preprocess_s3dis.py --dataset_root ${RAW_S3DIS_DIR} --output_root ${PROCESSED_S3DIS_DIR}
FileNotFoundError: /scratch/point_transformer/Pointcept/S3DIS/Area_1/Area_1_alignmentAngle.txt not found

can you help

**Comment by Satyapalsinh10** [comment]
there is no Area_1_alignmentAngle.txt file in Area_1

**Comment by Gofinge** [comment]
Hi, could you show me your full script and I will check it? There is no `alignmentAngle.txt` in the S3DIS aligned angle version of the raw dataset.

**Comment by xqq12121** [comment]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/xqq/developer/ide/anaconda3/envs/pcr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/xqq/developer/ide/anaconda3/envs/pcr/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/xqq/developer/code/python/PointTransformerV2-main/pcr/datasets/preprocessing/s3dis/preprocess_s3dis.py", line 40, in parse_room
    obj = np.loadtxt(object_path)
  File "/home/xqq/developer/ide/anaconda3/envs/pcr/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1356, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/home/xqq/developer/ide/anaconda3/envs/pcr/lib/python3.8/site-packages/numpy/lib/npyio.py", line 999, in _read
    arr = _load_from_filelike(
ValueError: the number of columns changed from 6 to 5 at row 180389; use `usecols` to select a subset and avoid this error
"""

The above exception was the direct cause of the following exception:

how about this ,I run the pcr/datasets/preprocessing/s3dis/preprocess_s3dis.py

**Comment by Gofinge** [comment]
Hi, this repo is no longer maintain, please considering shift to our new codebase, Pointcept.
