### ISSUE TITLE
python pcr/datasets/preprocessing/s3dis/preprocess_s3dis.py --dataset_root ${RAW_S3DIS_DIR} --output_root ${PROCESSED_S3DIS_DIR}

### ISSUE THREAD

**Issue by shenggebiya** [Gofinge/PointTransformerV2#39]
Traceback (most recent call last):
  File "pcr/datasets/preprocessing/s3dis/preprocess_s3dis.py", line 114, in <module>
    main_process()
  File "pcr/datasets/preprocessing/s3dis/preprocess_s3dis.py", line 107, in main_process
    pool.starmap(parse_room, [(room, opt.dataset_root, opt.save_root, opt.parse_normals)
  File "pcr/datasets/preprocessing/s3dis/preprocess_s3dis.py", line 107, in <listcomp>
    pool.starmap(parse_room, [(room, opt.dataset_root, opt.save_root, opt.parse_normals)
AttributeError: 'Namespace' object has no attribute 'save_root'

**Comment by Gofinge** [comment]
Aha, replace `--output_root` with `--save_root`. I fix the bug in our new codebase [Pointcept](https://github.com/Pointcept/Pointcept). I will also fix the bug here, thanks.

**Comment by Gofinge** [comment]
It seems that I already fix the bug long time ago, maybe you can pull the code again?

**Comment by shenggebiya** [comment]
thanks
