### ISSUE TITLE
S3DIS Data process

### ISSUE THREAD

**Issue by xqq12121** [Gofinge/PointTransformerV2#44]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
File "/home/xqq/developer/ide/anaconda3/envs/pcr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
result = (True, func(*args, **kwds))
File "/home/xqq/developer/ide/anaconda3/envs/pcr/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
return list(itertools.starmap(args[0], args[1]))
File "/home/xqq/developer/code/python/PointTransformerV2-main/pcr/datasets/preprocessing/s3dis/preprocess_s3dis.py", line 40, in parse_room
obj = np.loadtxt(object_path)
File "/home/xqq/developer/ide/anaconda3/envs/pcr/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1356, in loadtxt
arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
File "/home/xqq/developer/ide/anaconda3/envs/pcr/lib/python3.8/site-packages/numpy/lib/npyio.py", line 999, in _read
arr = _load_from_filelike(
ValueError: the number of columns changed from 6 to 5 at row 180389; use usecols to select a subset and avoid this error
"""

The above exception was the direct cause of the following exception:

I run the pcr/datasets/preprocessing/s3dis/preprocess_s3dis.py

**Comment by xqq12121** [comment]
Is this a problem with the dataset? If so, can you provide a download link

**Comment by Gofinge** [comment]
Yes, this dataset exist a problem, download link is available in our new codebase readme.

**Comment by xqq12121** [comment]
Where can I find  new codebase readme.

**Comment by xqq12121** [comment]
Is PointCept？ ok I konw, thank you

**Comment by Gofinge** [comment]
> Is PointCept？ ok I konw, thank you

yes
