### ISSUE TITLE
s3dis  array  concatenate

### ISSUE THREAD

**Issue by ILOVEppt** [Gofinge/PointTransformerV2#45]
Hi,here is a problem!
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/jsjlab/anaconda3/envs/pcr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/jsjlab/anaconda3/envs/pcr/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "pcr/datasets/preprocessing/s3dis/preprocess_s3dis.py", line 60, in parse_room
    room_coords = np.ascontiguousarray(np.vstack(room_coords))
  File "<__array_function__ internals>", line 5, in vstack
  File "/home/jsjlab/anaconda3/envs/pcr/lib/python3.8/site-packages/numpy/core/shape_base.py", line 283, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: need at least one array to concatenate
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pcr/datasets/preprocessing/s3dis/preprocess_s3dis.py", line 116, in <module>
    main_process()
  File "pcr/datasets/preprocessing/s3dis/preprocess_s3dis.py", line 109, in main_process
    pool.starmap(parse_room, [(room, opt.dataset_root, opt.output_root, opt.parse_normals)
  File "/home/jsjlab/anaconda3/envs/pcr/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/jsjlab/anaconda3/envs/pcr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
ValueError: need at least one array to concatenate

Can you help me?Thank you!

**Comment by baby-penguin** [comment]
There maybe some files like ._celing_1.txt in your dataset, in preprocess.py, use `if ((room_name != ".DS_Store" and not room_name.startswith(".") ) and ".txt" not in room_name)]`
